### ISSUE TITLE
Add `COMPILER` option in cmake to make possible compile project via gcc (default) and clang compilers.

### ISSUE THREAD

**Issue by KorespondentAda** [Fikafusik/learning_space#2]
For example:
`cmake --build . -DCOMPILER:STRING=GCC|CLANG`

**Comment by KorespondentAda** [comment]
Command `cmake --build` use preconfigured compiler, so to choose compiler we need to set corresponding variables on creating configuration, environment ones like:`C|CXX=gcc|clang cmake <...>`, or directly cmake variables: `cmake <...> -DCMAKE_{C,CXX}_COMPILER=gcc|clang`.
As choosing compiler is cmake built-in feature, I think issue can be closed.

**Comment by Fikafusik** [comment]
@KorespondentAda, thanks for your research, it's helpful information
